#+TITLE:DeckInfo

Project to gain insight into an MTG Deck's statistics.
Was rebased from *deckStats* because a web page by that name (that also includes
this functionality) was created.
* General Information
** Deck Loading
   Deck loading behavior is in the ~ebarrientos.deckStats.load~ package, through
   the ~DeckLoader~ trait. The main implementation is ~XMLDeckLoader~, that uses
   the [[https://cockatrice.github.io][Cockatrice]] xml format.
** Loading Card information
   The ~ebarrientos.deckStats.load~  package also contains classes for loading
   card information. There are seeral implementations, depending on where it
   queries information from.
   - Local storage
     - XMLCardLoader    :: Load from an XML file.
     - H2DBDoobieLoader :: Load from an H2DB database
   - Remote
     - MagicIOLoader      :: Load from =api.magicthegathering.io=
     - ScryCardLoader     :: /Deprecated/
     - MagicAPICardLoader :: Load from http://stegriff.co.uk/ /Deprecated/
   - Other
     - WeakCachedLoader :: Card info cache. It requires a helper loader to get
       information the first time. Useful to avoid loading from remote sources
       more than once.
     - MtgJsonLoader    :: Loads cards that are in MtgJson format. It takes the
       JSon directly and transforms it into a card.
** Calculating deck information
   The object [[file:core/src/main/scala/ebarrientos/deckStats/math/Calc.scala::package ebarrientos.deckStats.math][ebarrientos.deckStats.math.Calc]] offers methods for calculating
   metrics of a deck. It has methods for obtaining averages, counts, etc.
   Also, [[file:core/src/main/scala/ebarrientos/deckStats/queries/DeckCalc.scala::package ebarrientos.deckStats.queries][ebarrientos.deckStats.queries.DeckCalc]] provides a deck level version
   that relies internally on ~Calc~.
* Running
There are two main runners:
** Web Based
Upload a deck through the interface, see your information.
*** Running
~sbt playWeb/run~
** CLI
Transitional interface meant to prove everything else worked. Shows information
on the console.
*** Running
~sbt cliView/run <path/to/deck>~
